# Generated by Django 2.2.4 on 2019-10-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pclass', models.CharField(max_length=10)),
                ('Sex', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
                ('SibSp', models.IntegerField()),
                ('Parch', models.IntegerField()),
                ('Embarked', models.CharField(blank=True, max_length=10, null=True)),
                ('Survived', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
